/**
 * sqlite-test-db.ts
 *
 * Provides createSqliteTestDb() — a factory that creates an isolated SQLite
 * database file for integration tests without touching the running :3001 server
 * or the default @prisma/client (PostgreSQL).
 *
 * Each call creates a unique .tmp/sqlite-test/test-<pid>-<label>-<n>.db file,
 * applies SQLITE_INIT_SQL via bun:sqlite, then returns a PrismaClient from the
 * test-only generated client (src/generated/prisma-sqlite/).
 * Call dispose() in afterAll to disconnect and delete the file + WAL/SHM artefacts.
 */

import Database from 'bun:sqlite';
import fs from 'fs';
import path from 'path';
import { SQLITE_INIT_SQL } from '../../src/generated/sqlite-init-sql';

// NOTE: Counter is process-scoped and deterministic — no Date.now()/Math.random().
let counter = 0;

const TMP_DIR = path.join(import.meta.dir, '../../../.tmp/sqlite-test');

/** The shape returned by createSqliteTestDb. */
export type SqliteTestDb = {
  /** SQLite-backed PrismaClient pointing at the temp DB file. */
  // HACK(agent): typed as any — PrismaClient from the generated path is only known at runtime.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  prisma: any;
  /** Absolute path of the temp DB file (for diagnostics). */
  dbPath: string;
  /** Disconnect Prisma and delete the DB file (+ WAL/SHM). Call in afterAll. */
  dispose: () => Promise<void>;
};

/**
 * Creates an isolated SQLite test database and returns a connected PrismaClient.
 *
 * @param label - Short identifier used in the filename (e.g. 'import', 'export').
 * @returns SqliteTestDb with prisma client, dbPath, and dispose() / テスト用 SQLite 接続セット
 */
export async function createSqliteTestDb(label: string): Promise<SqliteTestDb> {
  fs.mkdirSync(TMP_DIR, { recursive: true });

  const dbPath = path.join(TMP_DIR, `test-${process.pid}-${label}-${++counter}.db`);

  // Apply DDL via bun:sqlite before Prisma connects.
  // NOTE: ensureDesktopSqliteDatabase is intentionally NOT called here —
  // the test uses a deterministic DDL snapshot (SQLITE_INIT_SQL), not self-heal.
  const rawDb = new Database(dbPath);
  rawDb.exec(SQLITE_INIT_SQL);
  rawDb.close();

  // Dynamically import the test-only SQLite Prisma client.
  // NOTE: The path is relative to this file (tests/integration/sqlite/).
  // src/generated/prisma-sqlite/ is generated by `bun run db:prepare:sqlite:test`
  // and is excluded from git (see .gitignore).
  const { PrismaClient } = (await import(
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore — generated path not visible to tsc at compile time
    '../../../src/generated/prisma-sqlite/index.js'
  )) as { PrismaClient: new (opts: object) => import('@prisma/client').PrismaClient };

  const prisma = new PrismaClient({
    datasourceUrl: `file:${path.resolve(dbPath)}`,
  });

  const dispose = async (): Promise<void> => {
    await prisma.$disconnect();
    for (const suffix of ['', '-wal', '-shm']) {
      try {
        fs.unlinkSync(dbPath + suffix);
      } catch {
        // File may not exist (WAL/SHM are only created on write).
      }
    }
  };

  return { prisma, dbPath, dispose };
}
