/**
 * adversarial-diff-review.jury-diff.test
 *
 * buildJuryDiffText must tell the jury which changed files a generator owns.
 * Task 1107 was failed for scope drift on "無関係な既存キー" in
 * rapitas-frontend/messages/{en,ja}.json — regenerated by generate-messages.mjs
 * on every pretest, so their churn is the build, not the agent's scope. With no
 * marking in the diff, scope creep was the only reading available.
 *
 * The file already carries the same shape of guard for truncation ("do not call
 * a manifest-listed file unimplemented just because its patch is cut"), so this
 * follows that precedent rather than inventing a new mechanism.
 */
import { describe, test, expect } from 'bun:test';
import { buildJuryDiffText } from './adversarial-diff-review';

const file = (filename: string, patch = '@@ -1 +1 @@\n-a\n+b') => ({
  filename,
  status: 'modified',
  additions: 1,
  deletions: 1,
  patch,
});

describe('buildJuryDiffText — 生成物の明示', () => {
  test('生成ファイルに印と理由が付く', () => {
    const text = buildJuryDiffText([file('rapitas-frontend/messages/ja.json')]);
    expect(text).toContain('rapitas-frontend/messages/ja.json');
    expect(text).toContain('生成物');
    expect(text).toContain('generate-messages.mjs');
  });

  test('生成物が含まれるときだけ陪審への注意書きが出る', () => {
    const withGen = buildJuryDiffText([file('rapitas-frontend/messages/en.json')]);
    expect(withGen).toContain('スコープ逸脱と判定しないでください');

    const handWritten = buildJuryDiffText([file('rapitas-backend/services/workflow/x.ts')]);
    expect(handWritten).not.toContain('スコープ逸脱と判定しないでください');
  });

  // The dangerous direction: a hand-written file must never be excused.
  test('手書きファイルには生成物の印を付けない', () => {
    const text = buildJuryDiffText([
      file('rapitas-frontend/messages/fragments/ja/01-common.json'),
      file('rapitas-backend/services/workflow/halt-release.ts'),
    ]);
    expect(text).not.toContain('生成物');
  });

  test('混在時は生成物だけに印が付く', () => {
    const text = buildJuryDiffText([
      file('rapitas-backend/services/workflow/halt-release.ts'),
      file('rapitas-frontend/messages/ja.json'),
    ]);
    const manifest = text.split('### 差分本文')[0]!;
    const genLine = manifest.split('\n').find((l) => l.includes('messages/ja.json'));
    const srcLine = manifest.split('\n').find((l) => l.includes('halt-release.ts'));
    expect(genLine).toContain('生成物');
    expect(srcLine).not.toContain('生成物');
  });

  // The pre-existing contract must survive: the manifest stays complete and the
  // truncation banner still appears for long patches.
  test('既存の省略バナーは壊れていない', () => {
    const long = '@@\n' + '+x\n'.repeat(4000);
    const text = buildJuryDiffText([file('rapitas-backend/services/a.ts', long)], 500);
    expect(text).toContain('[省略');
    expect(text).toContain('未実装');
  });

  test('ファイルが無ければ空文字', () => {
    expect(buildJuryDiffText([])).toBe('');
  });
});
