/**
 * PRHelpers
 *
 * Helper functions for building PR bodies, reading workflow files, and
 * accessing internal executor state (safety report, session data).
 * Does not define any route handlers.
 */
import { readFile } from 'fs/promises';
import { join } from 'path';
import { prisma } from '../../../config/database';
import { createLogger } from '../../../config';
import type { createParallelExecutor } from '../../../services/parallel-execution';
import type { SafetyReport } from '../../../services/parallel-execution';
import { analyzePlanDeviation } from './analysis-helpers';

const log = createLogger('routes:parallel-execution:pr-helpers');

/** Internal shape of a parallel execution session stored in the executor. */
export type ParallelExecutionSession = {
  taskBranches: Map<number, string>;
  workingDirectory: string;
};

/**
 * Build a rich PR body with implementation summary, plan comparison, and validation.
 *
 * @param taskId - Task ID / タスクID
 * @param task - Task record with relations / リレーション付きタスクレコード
 * @param workingDirectory - Repository root / リポジトリルート
 * @returns Formatted PR body markdown / フォーマット済みPRボディMarkdown
 */
export async function buildPRBody(
  taskId: number,
  task: { title: string; description: string | null },
  workingDirectory: string,
): Promise<string> {
  const sections: string[] = [];

  sections.push(`## Summary\n\nTask #${taskId}: ${task.title}`);
  if (task.description) {
    sections.push(`### Description\n\n${task.description.slice(0, 500)}`);
  }

  const planContent = await readWorkflowFile(taskId, 'plan');
  const verifyContent = await readWorkflowFile(taskId, 'verify');

  if (planContent) {
    sections.push(
      `### Implementation Plan\n\n<details>\n<summary>Original Plan</summary>\n\n${planContent}\n\n</details>`,
    );
  }
  if (verifyContent) {
    sections.push(`### Verification Report\n\n${verifyContent}`);
  }

  try {
    const { execSync } = await import('child_process');
    const diffStat = execSync('git diff --stat develop...HEAD', {
      cwd: workingDirectory,
      encoding: 'utf8',
      timeout: 10000,
    }).trim();
    if (diffStat) {
      sections.push(`### Changed Files\n\n\`\`\`\n${diffStat}\n\`\`\``);
    }
  } catch {
    /* non-fatal */
  }

  if (planContent && verifyContent) {
    const deviation = analyzePlanDeviation(planContent, verifyContent);
    if (deviation) sections.push(`### Plan Deviation\n\n${deviation}`);
  }

  sections.push('---\n🤖 Generated by Rapitas AI Agent');
  return sections.join('\n\n');
}

/**
 * Read a workflow file for a task.
 *
 * @param taskId - Task ID / タスクID
 * @param fileType - Workflow file type (plan, verify, etc.) / ワークフローファイルタイプ
 * @returns File contents or null if not found / ファイル内容またはnull
 */
export async function readWorkflowFile(taskId: number, fileType: string): Promise<string | null> {
  try {
    const task = await prisma.task.findUnique({
      where: { id: taskId },
      include: { theme: { include: { category: true } } },
    });
    if (!task) return null;

    const categoryDir = task.theme?.categoryId ? String(task.theme.categoryId) : '0';
    const themeDir = task.themeId ? String(task.themeId) : '0';
    const filePath = join(
      process.cwd(),
      'tasks',
      categoryDir,
      themeDir,
      String(taskId),
      `${fileType}.md`,
    );
    return await readFile(filePath, 'utf-8');
  } catch {
    return null;
  }
}

/**
 * Retrieve safety report from executor's internal coordinator shared data.
 *
 * @param executor - Parallel executor instance / パラレルエクゼキューターインスタンス
 * @param sessionId - Session ID / セッションID
 * @returns Safety report or null / セーフティレポートまたはnull
 */
export function getSafetyReportFromExecutor(
  executor: ReturnType<typeof createParallelExecutor>,
  sessionId: string,
): SafetyReport | null {
  // NOTE: Access coordinator via executor's prototype — typed as 'any' because
  // coordinator is private. A public accessor would be preferred long-term.
  // HACK(agent): Private field access needed until a public getSafetyReport() is added.
  const internal = executor as unknown as Record<string, unknown>;
  const coordinator = internal['coordinator'] as
    | { getSharedData: (key: string) => unknown }
    | undefined;
  if (!coordinator) return null;
  return (coordinator.getSharedData(`safety-report:${sessionId}`) as SafetyReport) ?? null;
}

/**
 * Retrieve session data from executor's internal sessions map.
 *
 * @param executor - Parallel executor instance / パラレルエクゼキューターインスタンス
 * @param sessionId - Session ID / セッションID
 * @returns Session data or null / セッションデータまたはnull
 */
export function getSessionFromExecutor(
  executor: ReturnType<typeof createParallelExecutor>,
  sessionId: string,
): { taskBranches: Map<number, string>; workingDirectory: string } | null {
  // HACK(agent): Private field access needed until a public getSession() is added.
  const internal = executor as unknown as Record<string, unknown>;
  const sessions = internal['sessions'] as
    | Map<string, ParallelExecutionSession>
    | undefined;
  if (!sessions) return null;
  const session = sessions.get(sessionId);
  if (!session) return null;
  return { taskBranches: session.taskBranches, workingDirectory: session.workingDirectory };
}

export { log as prHelpersLog };
