/**
 * Verification Job Store
 *
 * Persists implementer self-verification jobs as `TimelineEvent` rows (no new
 * Prisma model — task 899) and derives running/completed/failed/interrupted
 * state from the (at most two) rows a job ever writes. `TimelineEvent` is
 * create-only in this codebase (see dry-run-orchestrator.ts precedent), so
 * state is always derived, never updated in place. Not responsible for
 * running the verification gate itself — see verification-job-runner.ts.
 */
import { randomUUID } from 'crypto';
import type { CommandEvidence } from '../agents/verification/command-evidence';
import { appendEvent, queryEvents } from '../memory/timeline';
import type { VerificationCheck } from '../agents/verification/automated-verifier';

/**
 * Generated once per process boot — doubles as the "executionCodeVersion"
 * identifier. No build-version concept (git SHA / package version) existed
 * for this purpose, and a process restart is the closest available proxy for
 * "the running code may have changed" in this project's dev workflow.
 */
export const PROCESS_INSTANCE_ID = randomUUID();

/**
 * A `running` job older than this (ms) with no finish event is treated as
 * interrupted even within the same process — a defensive backstop for a
 * background task that died without writing its finish event.
 */
export const STALE_RUNNING_MS = Number(process.env.RAPITAS_VERIFY_JOB_STALE_MS) || 30 * 60 * 1000;

const MAX_CHECK_DETAILS_CHARS = 4_000;
const MAX_MARKDOWN_CHARS = 8_000;

function truncate(text: string, max: number): string {
  return text.length > max ? `${text.slice(0, max)}…(truncated)` : text;
}

/**
 * Identity of the job's execution target (task 916): which command was run,
 * against which worktree and git revision. Recorded on both the start and
 * finish events so a job can be traced even if the finish event is missing
 * (interrupted run).
 */
export interface VerificationJobContext {
  operation: string;
  worktreePath: string;
  revision: string | null;
}

/** Outcome of a completed background verification run, persisted as the finish event. */
export interface VerificationJobOutcome {
  status: 'completed' | 'failed';
  ok?: boolean;
  unverifiable?: boolean;
  checks?: VerificationCheck[];
  summary?: unknown;
  markdown?: string;
  error?: string;
  durationMs?: number;
  fingerprintAtFinish?: string | null;
  /** Actual observed subprocess outcomes, independent of the gate verdict. */
  commands?: CommandEvidence[];
}

/** Derived state of a verification job, ready for the GET status handler to shape into a response. */
export interface VerificationJobRecord {
  runId: string;
  taskId: number;
  status: 'running' | 'completed' | 'failed' | 'interrupted';
  startedAt: string;
  finishedAt?: string;
  ok?: boolean;
  unverifiable?: boolean;
  checks?: VerificationCheck[];
  summary?: unknown;
  markdown?: string;
  error?: string;
  durationMs?: number;
  operation?: string;
  worktreePath?: string;
  revision?: string | null;
  commands?: CommandEvidence[];
}

function correlationIdFor(taskId: number): string {
  return `verify-job-${taskId}`;
}

/**
 * Record that a verification job has started. Called synchronously (the fast
 * path) before the POST handler returns, so its runId can be included in the
 * response immediately.
 *
 * @param taskId - Task the job runs against. / 対象タスクID
 * @param runId - Job identifier generated by the caller. / ジョブID
 * @param fingerprint - Input identity at start time (from computeVerificationCacheKey), or null when unavailable. / 開始時点の入力識別子
 * @param context - Command/worktree/revision identity for this run (task 916). / 実行コマンド・worktree・revision
 */
export async function recordJobStart(
  taskId: number,
  runId: string,
  fingerprint: string | null,
  context: VerificationJobContext,
): Promise<void> {
  await appendEvent({
    eventType: 'verification_job_started',
    actorType: 'system',
    correlationId: correlationIdFor(taskId),
    payload: {
      runId,
      taskId,
      fingerprint,
      processInstanceId: PROCESS_INSTANCE_ID,
      executionCodeVersion: PROCESS_INSTANCE_ID,
      startedAt: new Date().toISOString(),
      operation: context.operation,
      worktreePath: context.worktreePath,
      revision: context.revision,
    },
  });
}

/**
 * Record that a verification job has finished (completed or failed). Called
 * from the background continuation AFTER the POST response has already been
 * sent — this write happens independently of the client's connection state.
 *
 * @param taskId - Task the job ran against. / 対象タスクID
 * @param runId - Job identifier matching the start event. / ジョブID
 * @param outcome - Terminal result to persist. / 終了時の結果
 */
export async function recordJobFinish(
  taskId: number,
  runId: string,
  outcome: VerificationJobOutcome,
): Promise<void> {
  const checks = outcome.checks?.map((check) => ({
    ...check,
    details: truncate(check.details, MAX_CHECK_DETAILS_CHARS),
  }));
  await appendEvent({
    eventType: 'verification_job_finished',
    actorType: 'system',
    correlationId: correlationIdFor(taskId),
    payload: {
      runId,
      taskId,
      status: outcome.status,
      ok: outcome.ok,
      unverifiable: outcome.unverifiable,
      checks,
      summary: outcome.summary,
      markdown:
        outcome.markdown !== undefined ? truncate(outcome.markdown, MAX_MARKDOWN_CHARS) : undefined,
      error: outcome.error,
      finishedAt: new Date().toISOString(),
      durationMs: outcome.durationMs,
      fingerprintAtFinish: outcome.fingerprintAtFinish,
      commands: outcome.commands,
    },
  });
}

interface StartPayload {
  runId: string;
  taskId: number;
  fingerprint: string | null;
  processInstanceId: string;
  executionCodeVersion: string;
  startedAt: string;
  operation?: string;
  worktreePath?: string;
  revision?: string | null;
}

interface FinishPayload {
  runId: string;
  taskId: number;
  status: 'completed' | 'failed';
  ok?: boolean;
  unverifiable?: boolean;
  checks?: VerificationCheck[];
  summary?: unknown;
  markdown?: string;
  error?: string;
  finishedAt: string;
  durationMs?: number;
  fingerprintAtFinish?: string | null;
  commands?: CommandEvidence[];
}

/** Derive `running`/`completed`/`failed`/`interrupted` from a job's start row and (if any) finish row. Never mutates either row. */
function deriveRecord(
  taskId: number,
  runId: string,
  start: StartPayload,
  finish: FinishPayload | null,
): VerificationJobRecord {
  if (finish) {
    return {
      runId,
      taskId,
      status: finish.status,
      startedAt: start.startedAt,
      finishedAt: finish.finishedAt,
      ok: finish.ok,
      unverifiable: finish.unverifiable,
      checks: finish.checks,
      summary: finish.summary,
      markdown: finish.markdown,
      error: finish.error,
      durationMs: finish.durationMs,
      operation: start.operation,
      worktreePath: start.worktreePath,
      revision: start.revision,
      commands: finish.commands,
    };
  }
  const startedAtMs = new Date(start.startedAt).getTime();
  const isStale = !Number.isFinite(startedAtMs) || Date.now() - startedAtMs >= STALE_RUNNING_MS;
  const isSameProcess = start.processInstanceId === PROCESS_INSTANCE_ID;
  return {
    runId,
    taskId,
    status: isSameProcess && !isStale ? 'running' : 'interrupted',
    startedAt: start.startedAt,
    operation: start.operation,
    worktreePath: start.worktreePath,
    revision: start.revision,
  };
}

/**
 * Look up one verification job by runId, deriving its state from the
 * (at most two) TimelineEvent rows it wrote.
 *
 * @param taskId - Task the job belongs to. / 対象タスクID
 * @param runId - Job identifier to look up. / ジョブID
 * @returns The derived job record, or null when no start event exists. / 導出されたジョブ状態、無ければnull
 */
export async function getJobByRunId(
  taskId: number,
  runId: string,
): Promise<VerificationJobRecord | null> {
  const { events } = await queryEvents({ correlationId: correlationIdFor(taskId), limit: 200 });
  const start = events.find(
    (e) =>
      e.eventType === 'verification_job_started' && (e.payload as StartPayload).runId === runId,
  );
  if (!start) return null;
  const finish = events.find(
    (e) =>
      e.eventType === 'verification_job_finished' && (e.payload as FinishPayload).runId === runId,
  );
  return deriveRecord(
    taskId,
    runId,
    start.payload as StartPayload,
    (finish?.payload as FinishPayload | undefined) ?? null,
  );
}

/**
 * Look up the most recently started verification job for a task, deriving
 * its state the same way as {@link getJobByRunId}. Never starts a new job.
 *
 * @param taskId - Task to look up. / 対象タスクID
 * @returns The most recent job's derived record, or null when none exist. / 最新ジョブの導出状態、無ければnull
 */
export async function getLatestJob(taskId: number): Promise<VerificationJobRecord | null> {
  const { events } = await queryEvents({ correlationId: correlationIdFor(taskId), limit: 200 });
  const starts = events.filter((e) => e.eventType === 'verification_job_started');
  if (starts.length === 0) return null;
  const latestStart = starts.reduce((newest, current) =>
    new Date((current.payload as StartPayload).startedAt).getTime() >
    new Date((newest.payload as StartPayload).startedAt).getTime()
      ? current
      : newest,
  );
  return getJobByRunId(taskId, (latestStart.payload as StartPayload).runId);
}
