/**
 * panels.generated
 *
 * Auto-generated by scripts/generate-agents-panels.mjs — do not edit by hand.
 * Regenerate after adding/removing a panel's `panelMeta` export.
 */
import type { ComponentType } from 'react';
import { SystemStatusPanel } from './SystemStatusPanel';
import { RecoveryMetricsPanel } from './RecoveryMetricsPanel';
import { ErrorDiagnosisPanel } from './ErrorDiagnosisPanel';
import { ProbeMetricsPanel } from './ProbeMetricsPanel';
import { ResourceContentionPanel } from './ResourceContentionPanel';

export const AGENTS_PANELS: { id: string; Component: ComponentType }[] = [
  { id: 'system-status', Component: SystemStatusPanel },
  { id: 'recovery-metrics', Component: RecoveryMetricsPanel },
  { id: 'error-diagnosis', Component: ErrorDiagnosisPanel },
  { id: 'probe-metrics', Component: ProbeMetricsPanel },
  { id: 'resource-contention', Component: ResourceContentionPanel },
];
